### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ningen58** [RedaZt/SakugaGrabber#1]
Any fix for this?
https://i.imgur.com/dNIyUyt.png

**Comment by RedaZt** [comment]
Fixed, expect an update soon.

**Comment by SeanSakuga** [comment]
Waiting patiently for this <3

**Comment by RedaZt** [comment]
Hi, this issue's been resolved in the latest version, get it [here](https://github.com/RedaZt/SakugaGrabber/releases/tag/v2.0).

**Comment by ningen58** [comment]
Thanks, it's working fine now.
